// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEgIr2bq64na3QRUhri4naQmpmzDZKEfg',
    appId: '1:756390333326:web:90282e796886b5fee3b2df',
    messagingSenderId: '756390333326',
    projectId: 'smart-shop-da51a',
    authDomain: 'smart-shop-da51a.firebaseapp.com',
    storageBucket: 'smart-shop-da51a.firebasestorage.app',
    measurementId: 'G-F6HEF74B5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnETLhHnIN8yYkzspw-sj5aaYM90PJKGU',
    appId: '1:756390333326:android:a08253c22b2f8ae9e3b2df',
    messagingSenderId: '756390333326',
    projectId: 'smart-shop-da51a',
    storageBucket: 'smart-shop-da51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bG0dWYOqV6Hh1YYU_L2DgDzUyUASiuQ',
    appId: '1:756390333326:ios:4e87f7394ceb1376e3b2df',
    messagingSenderId: '756390333326',
    projectId: 'smart-shop-da51a',
    storageBucket: 'smart-shop-da51a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4bG0dWYOqV6Hh1YYU_L2DgDzUyUASiuQ',
    appId: '1:756390333326:ios:4e87f7394ceb1376e3b2df',
    messagingSenderId: '756390333326',
    projectId: 'smart-shop-da51a',
    storageBucket: 'smart-shop-da51a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEgIr2bq64na3QRUhri4naQmpmzDZKEfg',
    appId: '1:756390333326:web:8c16a98d8185a00ee3b2df',
    messagingSenderId: '756390333326',
    projectId: 'smart-shop-da51a',
    authDomain: 'smart-shop-da51a.firebaseapp.com',
    storageBucket: 'smart-shop-da51a.firebasestorage.app',
    measurementId: 'G-J2PW6SZ8ZN',
  );
}
